name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    needs: skip-draft
    name: Lint & Test
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/cache@v2.1.5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate DTOs from Notifications Service
        run: yarn generate:models
      - name: Eslint
        run: yarn lint
      - name: Build
        run: yarn build
